# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pttd < Formula
  desc "A push to talk daemon that allows global push to talk on Linux."
  homepage "https://github.com/atmelmicro/pttd"
  version "0.1.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/atmelmicro/pttd/releases/download/v0.1.1/pttd_0.1.1_linux_amd64.tar.gz"
    sha256 "d8347cbe3dd20efbd069b499c11020aee96af8a49fa9b73d56e84dad34506b6d"
    define_method(:install) do
      bin.install "pttd"
    end
  end

  service do
    run [opt_bin/"pttd"]
    working_dir var/"pttd"
    log_path var/"log/pttd.log"
    error_log_path var/"log/pttd-error.log"
    keep_alive true
  end
end
